apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: block-host-pid-ipc
spec:
  validationActions:
    - Deny
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
  validations:
    - message: "hostPID and hostIPC are not allowed."
      expression: >
        (!has(object.spec.hostPID) || object.spec.hostPID == false) && 
        (!has(object.spec.hostIPC) || object.spec.hostIPC == false)