apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: block-hostnetwork
spec:
  validationActions:
    - Deny
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
  validations:
    - message: "hostNetwork is not allowed."
      expression: >
        !has(object.spec.hostNetwork) ||
        object.spec.hostNetwork == false