apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-credentials
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform
  source:
    repoURL: https://github.com/GHARBIyasmine/kyverno-platform.git
    targetRevision: main
    path: infra/external-secrets
    directory:
      include: 'eso-credentials.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: secret-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true