apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostpath-app
  namespace: demo-orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostpath-app
  template:
    metadata:
      labels:
        app: hostpath-app
    spec:
      volumes:
        - name: host-vol
          hostPath:
            path: /etc
      containers:
        - name: app
          image: ghcr.io/gharbiyasmine/kyverno-demo:1.0.0
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
